  version: "3"
  services:
    flight-reservation:
      image: jaifee/selenium-docker
      environment:
      - BROWSER=${BROWSER}
      - HUB_HOST=hub
      - THREAD_COUNT=2
      - TEST_SUITE=flight-reservation.xml
      volumes:
        - ./output/flight-reservation:/home/selenium-docker/test-output
    vendor-portal:
      image: jaifee/selenium-docker
      environment:
        - BROWSER=${BROWSER}
        - HUB_HOST=hub
        - THREAD_COUNT=2
        - TEST_SUITE=vendor-portal.xml
      volumes:
        - ./output/vendor-portal:/home/selenium-docker/test-output
        - ./test-data/mike.json:/home/selenium-docker/test-data/vendor-portal/mike.json





